In [112]:
import numpy as np
import math
import collections

y = np.array([[45,85,-1],
            [50,43,-1],
            [40,80,-1],
            [55,42,-1],
            [200,43,-1],
            [48,40,-1],
            [195,41,-1],
            [43,87,-1],
            [190,40,-1]])

def f(net):
        return 2/(1+np.exp(-net)) -1

d = np.array([[1,-1,-1],
            [-1,1,-1],
            [1,-1,-1],
            [-1,1,-1],
            [-1,-1,1],
            [-1,1,-1],
            [-1,-1,1],
            [1,-1,-1],
            [-1,-1,1]])

max_0 = np.max(y[:, 0])
max_1 = np.max(y[:, 1])
min_0 = np.min(y[:, 0])
min_1 = np.min(y[:, 1])
print(max_0)
print(min_0)
print(max_1)
print(min_1)


def normalizare(y):
    y_norm = np.zeros((9, 3))
    y_norm[:, 0] = (y[:, 0] - min_0) / (max_0 - min_0)
    y_norm[:, 1] = (y[:, 1] - min_1) / (max_1 - min_1)
    y_norm[:, 2] = -1
    print(y_norm)
    return y_norm


y_norm = normalizare(y)
print(y_norm)



w = 2 * np.random.random((3, 3)) - 1

c = 1.5
E=0
Emax=0.001

while True:
    O = []
    for p in range(0,9):
        O.append(f(np.dot(w,y_norm[p])))
    O = np.array(O)   

    for p in range(9):    
        for j in range(3):
            for i in range(3):
                w[j, i] += c * (d[p, j] - O[p][j]) * (1 - O[p][j] ** 2) * y_norm[p, i]
                            
    E = 0
    for p in range(0, len(y)):
        for i in range(0, len(d[0]) - 2):
            E += (d[p, i] - O[p][i]) ** 2
    print(E)
    if E < Emax:
        break
    
temp = np.zeros(shape = (9,3))
for i in range(0, 9):
    for j in range(3):    
        if O[i][j] > 0.5:
            temp[i][j] = 1
        elif O[i][j] < -0.5:
            temp[i][j] = -1
        else:
            temp[i][j] = 0
print(temp)
for i in range(9):
    if temp[i][0] == S[0][0] and temp[i][1] == S[0][1] and temp[i][2] == S[0][2]:
        print(y[i],"este Scaun!")
    elif temp[i][0] == M[0][0] and temp[i][1] == M[0][1] and temp[i][2] == M[0][2]:
        print(y[i],"este Masa!")
    else:
        print(y[i],"este Pat!")
        
            

200
40
87
40
[[ 0.03125     0.95744681 -1.        ]
 [ 0.0625      0.06382979 -1.        ]
 [ 0.          0.85106383 -1.        ]
 [ 0.09375     0.04255319 -1.        ]
 [ 1.          0.06382979 -1.        ]
 [ 0.05        0.         -1.        ]
 [ 0.96875     0.0212766  -1.        ]
 [ 0.01875     1.         -1.        ]
 [ 0.9375      0.         -1.        ]]
[[ 0.03125     0.95744681 -1.        ]
 [ 0.0625      0.06382979 -1.        ]
 [ 0.          0.85106383 -1.        ]
 [ 0.09375     0.04255319 -1.        ]
 [ 1.          0.06382979 -1.        ]
 [ 0.05        0.         -1.        ]
 [ 0.96875     0.0212766  -1.        ]
 [ 0.01875     1.         -1.        ]
 [ 0.9375      0.         -1.        ]]
============W curent==========
[[ 0.53051866 -0.48795987 -0.91259903]
 [ 0.68118583  0.87976213 -0.11240845]
 [-0.43709352  0.96324847 -0.98839328]]
============O==========
[[0.22696857 0.45263594 0.73910169]
 [0.4278852  0.10517836 0.47094148]
 [0.24365582 0.40579846 0.71828334]
 [

 [ 9.05339246 -4.04664854  4.47946481]]
0.011435166209457953
============O==========
[[ 0.97161786 -0.98150563 -0.99937525]
 [-0.94159102  0.93782867 -0.96962338]
 [ 0.93990021 -0.9351354  -0.99927594]
 [-0.95724695  0.93285535 -0.95636172]
 [-0.99906997 -0.98581038  0.97363594]
 [-0.96372489  0.96898087 -0.96496201]
 [-0.99925595 -0.97221049  0.97059454]
 [ 0.98121884 -0.98610037 -0.99953032]
 [-0.99928662 -0.95550657  0.96431227]]
============W modificat==========
[[-4.44835865  8.52251862  3.77435309]
 [-8.94564417 -9.40284681 -4.60228994]
 [ 9.06056906 -4.04687775  4.48303482]]
0.011327505748712786
============O==========
[[ 0.97177535 -0.98161235 -0.99937747]
 [-0.94185081  0.93804373 -0.96971706]
 [ 0.94016017 -0.93541738 -0.99927866]
 [-0.95745035  0.93308923 -0.95648564]
 [-0.9990753  -0.98584225  0.97372922]
 [-0.96391334  0.96911314 -0.96507238]
 [-0.99926054 -0.97225462  0.97069224]
 [ 0.98133283 -0.98618598 -0.99953203]
 [-0.99929117 -0.95555824  0.9644228 ]]
============W 

============O==========
[[ 0.97794269 -0.98573852 -0.99947581]
 [-0.95225907  0.94698602 -0.97392099]
 [ 0.95063166 -0.9465745  -0.99939825]
 [-0.96554015  0.94273446 -0.96209324]
 [-0.99928245 -0.98767367  0.97766377]
 [-0.97133638  0.97451429 -0.97001498]
 [-0.99943743 -0.97508742  0.97482711]
 [ 0.98574398 -0.9894638  -0.9996078 ]
 [-0.99946557 -0.95926459  0.96911707]]
============W modificat==========
[[-4.50375146  9.03417291  4.00911971]
 [-9.27088866 -9.88745378 -4.81648638]
 [ 9.40273286 -4.0580953   4.65769889]]
0.007416390016582929
============O==========
[[ 0.97802346 -0.98579161 -0.99947724]
 [-0.95239874  0.94711281 -0.97398292]
 [ 0.95077297 -0.94672144 -0.99939998]
 [-0.96564788  0.94287032 -0.96217645]
 [-0.99928515 -0.98770467  0.97771991]
 [-0.97143423  0.97458921 -0.97008766]
 [-0.9994397  -0.97513813  0.97488639]
 [ 0.98580102 -0.98950557 -0.9996089 ]
 [-0.99946781 -0.95933417  0.96918469]]
============W modificat==========
[[-4.50456025  9.04160858  4.01252685]
 [

 [  9.706445    -4.06833904   4.8147946 ]]
0.005271273114895685
============O==========
[[ 0.98206262 -0.98842867 -0.99955336]
 [-0.95951795  0.95386705 -0.97731571]
 [ 0.95800394 -0.95416688 -0.99949164]
 [-0.97110719  0.95008695 -0.96667973]
 [-0.99941931 -0.98946105  0.9807166 ]
 [-0.97635286  0.97850853 -0.97399363]
 [-0.99955217 -0.97809699  0.97806441]
 [ 0.98862622 -0.99156655 -0.99966726]
 [-0.99957777 -0.96348858  0.97282696]]
============W modificat==========
[[ -4.54944802   9.45280048   4.20074551]
 [ -9.58995114 -10.29164417  -5.00417169]
 [  9.71047873  -4.0684765    4.81688287]]
0.005248275832484576
============O==========
[[ 0.98210934 -0.98845908 -0.9995543 ]
 [-0.95960198  0.95395026 -0.97735705]
 [ 0.95808962 -0.95425467 -0.99949276]
 [-0.97117123  0.95017568 -0.96673591]
 [-0.99942086 -0.98948358  0.98075355]
 [-0.97641008  0.97855592 -0.97404201]
 [-0.99955346 -0.97813591  0.97810378]
 [ 0.98865857 -0.99159014 -0.99966798]
 [-0.99957902 -0.96354426  0.97287231]]
==

 [  9.97206021  -4.07746581   4.95231288]]
0.003980745161013635
============O==========
[[ 0.98483388 -0.99023528 -0.99961091]
 [-0.96458029  0.9590245  -0.97988489]
 [ 0.96317989 -0.9594829  -0.99956037]
 [-0.97494791  0.95558348 -0.97018707]
 [-0.99951067 -0.99087447  0.98300557]
 [-0.97976259  0.98140477 -0.976997  ]
 [-0.99962763 -0.98057912  0.98051304]
 [ 0.99053034 -0.99296098 -0.99971121]
 [-0.99965103 -0.96708433  0.97565896]]
============W modificat==========
[[ -4.58670239   9.79194759   4.35571547]
 [ -9.87275354 -10.62698545  -5.16404668]
 [  9.9752584   -4.07757662   4.95396863]]
0.003967621599203266
============O==========
[[ 0.98486384 -0.99025487 -0.99961155]
 [-0.96463595  0.95908281 -0.979914  ]
 [ 0.96323696 -0.95954179 -0.99956114]
 [-0.97498993  0.95564561 -0.970227  ]
 [-0.99951166 -0.99089055  0.98303143]
 [-0.97979964  0.98143703 -0.97703099]
 [-0.99962843 -0.98060782  0.98054081]
 [ 0.99055075 -0.99297601 -0.9997117 ]
 [-0.99965181 -0.96712642  0.97569122]]
==

============W modificat==========
[[ -4.61160122  10.01760755   4.4587041 ]
 [-10.06980482 -10.85435696  -5.27370655]
 [ 10.15785863  -4.08393978   5.04849538]]
0.003294389229407315
============O==========
[[ 0.98646065 -0.99130194 -0.99964672]
 [-0.96763492  0.9622741  -0.98150857]
 [ 0.96631684 -0.96273516 -0.99960287]
 [-0.97724693  0.95904646 -0.9724215 ]
 [-0.99956404 -0.99176948  0.9844446 ]
 [-0.98178096  0.98318547 -0.97889121]
 [-0.9996712  -0.98219288  0.98206318]
 [ 0.99163318 -0.99377654 -0.99973847]
 [-0.99969313 -0.96946776  0.97746491]]
============W modificat==========
[[ -4.61196789  10.02092489   4.46021739]
 [-10.0727457  -10.85772449  -5.27533599]
 [ 10.16057709  -4.08403504   5.04990252]]
0.0032853996101892538
============O==========
[[ 0.98648284 -0.99131654 -0.99964722]
 [-0.96767706  0.96231963 -0.98153133]
 [ 0.96636019 -0.96278036 -0.99960346]
 [-0.97727854  0.95909499 -0.97245293]
 [-0.99956476 -0.99178198  0.98446473]
 [-0.98180859  0.98321017 -0.97891774]
 

 [-0.99972325 -0.97132333  0.97884908]]
============W modificat==========
[[ -4.6323453   10.2050253    4.54416869]
 [-10.23771292 -11.04571348  -5.36648312]
 [ 10.31286186  -4.08939679   5.12872198]]
0.002823252669194334
============O==========
[[ 0.98765966 -0.99209249 -0.99967407]
 [-0.96993238  0.96478204 -0.98276309]
 [ 0.96868301 -0.96521341 -0.99963518]
 [-0.97896611  0.96172067 -0.9741583 ]
 [-0.99960324 -0.99245528  0.98555226]
 [-0.98327808  0.98453557 -0.98035248]
 [-0.99970295 -0.9834518   0.98326263]
 [ 0.99243816 -0.99437681 -0.99975924]
 [-0.99972369 -0.97135148  0.97886997]]
============W modificat==========
[[ -4.63266053  10.20786931   4.54546512]
 [-10.2402869  -11.04863426  -5.36790178]
 [ 10.31523538  -4.08948075   5.12995036]]
0.0028166504983672333
============O==========
[[ 0.98767702 -0.99210397 -0.99967448]
 [-0.96996596  0.96481909 -0.98278162]
 [ 0.96871764 -0.96524986 -0.99963565]
 [-0.97899117  0.96176019 -0.97418404]
 [-0.99960381 -0.99246536  0.9855686 ]


 [ 10.41939914  -4.09317699   5.18385571]]
0.002543125650873555
============O==========
[[ 0.98841171 -0.9925904  -0.99969164]
 [-0.97139578  0.96640634 -0.98357595]
 [ 0.97019319 -0.96680856 -0.99965585]
 [-0.98005642  0.96345384 -0.97528884]
 [-0.99962777 -0.99289538  0.9862679 ]
 [-0.98422177  0.98539835 -0.98129816]
 [-0.9997227  -0.98427034  0.98404069]
 [ 0.9929394  -0.99475288 -0.99977256]
 [-0.99974264 -0.97258792  0.97978525]]
============W modificat==========
[[ -4.64671478  10.3345479    4.60319672]
 [-10.35565194 -11.17922884  -5.43139566]
 [ 10.42156119  -4.09325395   5.18497451]]
0.0025377690067924954
============O==========
[[ 0.98842641 -0.99260015 -0.99969199]
 [-0.97142457  0.9664385  -0.98359205]
 [ 0.97022293 -0.96684008 -0.99965626]
 [-0.98007783  0.96348817 -0.97531126]
 [-0.99962825 -0.99290405  0.98628206]
 [-0.98424025  0.98541534 -0.98131688]
 [-0.99972309 -0.98428656  0.9840561 ]
 [ 0.99294917 -0.99476023 -0.99977283]
 [-0.99974301 -0.97261252  0.97980341]]
=

============W modificat==========
[[ -4.65920483  10.44693459   4.65439254]
 [-10.45908714 -11.29587776  -5.48819524]
 [ 10.51682799  -4.09665495   5.23427018]]
0.002313632233899578
============O==========
[[ 0.98905347 -0.99301649 -0.99970689]
 [-0.97265946  0.96782482 -0.98428592]
 [ 0.97149915 -0.96819716 -0.99967374]
 [-0.98099481  0.96496837 -0.97627977]
 [-0.99964868 -0.99327636  0.98689154]
 [-0.98503017  0.98614412 -0.98212335]
 [-0.99973945 -0.98498599  0.98472084]
 [ 0.99336474 -0.99507342 -0.9997841 ]
 [-0.99975868 -0.9736767   0.98058797]]
============W modificat==========
[[ -4.65946415  10.44926604   4.65545437]
 [-10.46124292 -11.29830522  -5.48937794]
 [ 10.51881311  -4.09672603   5.23529733]]
0.002309199197705415
============O==========
[[ 0.98906611 -0.9930249  -0.99970719]
 [-0.9726845   0.96785308 -0.98430006]
 [ 0.97152505 -0.96822479 -0.99967409]
 [-0.98101338  0.96499856 -0.97629955]
 [-0.99964909 -0.99328392  0.98690396]
 [-0.98504613  0.98615891 -0.98213979]
 [

 [-0.999778   -0.97504336  0.98159247]]
============W modificat==========
[[ -4.67604187  10.59815581   4.7232465 ]
 [-10.59969158 -11.45393704  -5.56525334]
 [ 10.6462829   -4.10130708   5.30124842]]
0.0020430612033030078
============O==========
[[ 0.98984451 -0.99354312 -0.99972598]
 [-0.97423759  0.96961578 -0.98518227]
 [ 0.97313251 -0.96994637 -0.99969607]
 [-0.98216249  0.96688209 -0.97753578]
 [-0.9996744  -0.99375218  0.98767693]
 [-0.98603094  0.98707517 -0.98316408]
 [-0.99975994 -0.98588944  0.98558037]
 [ 0.99388584 -0.99546781 -0.99979853]
 [-0.99977826 -0.97506188  0.98160606]]
============W modificat==========
[[ -4.67627138  10.60021491   4.7241838 ]
 [-10.60161652 -11.45609761  -5.56630727]
 [ 10.64805505  -4.10137101   5.30216525]]
0.002039605042915561
============O==========
[[ 0.98985488 -0.99355003 -0.99972624]
 [-0.97425844  0.96963958 -0.98519418]
 [ 0.97315411 -0.9699696  -0.99969637]
 [-0.98217788  0.96690754 -0.97755251]
 [-0.99967473 -0.99375846  0.98768735]


============W modificat==========
[[ -4.69349498  10.75458024   4.79443209]
 [-10.74664956 -11.61867525  -5.64564839]
 [ 10.7815782   -4.10620667   5.37123878]]
0.0017965317580857705
============O==========
[[ 0.9906033  -0.9940495  -0.99974462]
 [-0.97577457  0.97137949 -0.98606474]
 [ 0.97472584 -0.9716664  -0.99971779]
 [-0.98329498  0.96876856 -0.97877803]
 [-0.99969902 -0.99421432  0.98844788]
 [-0.9869958   0.98798016 -0.98418743]
 [-0.99977945 -0.98677783  0.98642752]
 [ 0.99438218 -0.99584507 -0.99981259]
 [-0.99979684 -0.97643612  0.98261373]]
============W modificat==========
[[ -4.69369724  10.75639105   4.79525593]
 [-10.74835898 -11.62058927  -5.64658283]
 [ 10.78315205  -4.10626389   5.37205291]]
0.001793860033258637
============O==========
[[ 0.99061175 -0.99405515 -0.99974483]
 [-0.97579182  0.97139938 -0.9860747 ]
 [ 0.97474373 -0.97168579 -0.99971804]
 [-0.98330766  0.96878985 -0.97879208]
 [-0.99969929 -0.99421949  0.98845657]
 [-0.98700657  0.9879903  -0.98419897]
 

 [-0.999812   -0.97760278  0.98346805]]
============W modificat==========
[[ -4.70916867  10.89477881   4.85820248]
 [-10.87950594 -11.76731109  -5.71823121]
 [ 10.9039123   -4.11066986   5.43451591]]
0.0016010412246417484
============O==========
[[ 0.99123555 -0.99447211 -0.99976039]
 [-0.97707428  0.97288479 -0.98681757]
 [ 0.97607514 -0.9731336  -0.9997361 ]
 [-0.9842488   0.97038026 -0.9798425 ]
 [-0.9997195  -0.99460312  0.98910367]
 [-0.9878038   0.98874287 -0.98505938]
 [-0.99979559 -0.98753417  0.98715096]
 [ 0.99479294 -0.99615832 -0.99982447]
 [-0.99981217 -0.9776161   0.9834778 ]]
============W modificat==========
[[ -4.70934926  10.89639264   4.85893637]
 [-10.881041   -11.76902715  -5.71906939]
 [ 10.90532597  -4.11072162   5.43524708]]
0.001598919887762744
============O==========
[[ 0.99124258 -0.99447681 -0.99976056]
 [-0.97708883  0.9729017  -0.98682603]
 [ 0.97609025 -0.97315009 -0.99973631]
 [-0.98425946  0.97039839 -0.97985449]
 [-0.99971973 -0.99460746  0.98911103]


0.0014218712674458711
============O==========
[[ 0.99184308 -0.99487849 -0.99977573]
 [-0.97834103  0.97436314 -0.98755646]
 [ 0.9773919  -0.97457466 -0.99975386]
 [-0.98517489  0.97196473 -0.98089175]
 [-0.99973916 -0.99497948  0.9897455 ]
 [-0.98858399  0.9894829  -0.98591416]
 [-0.99981098 -0.98827465  0.9878617 ]
 [ 0.99518508 -0.99645809 -0.999836  ]
 [-0.99982676 -0.97878077  0.98433006]]
============W modificat==========
[[ -4.72551241  11.04069915   4.92454541]
 [-11.01878728 -11.92291774  -5.79424658]
 [ 11.03220254  -4.11538389   5.50086572]]
0.001420198687409165
============O==========
[[ 0.99184889 -0.99488238 -0.99977588]
 [-0.97835324  0.97437744 -0.9875636 ]
 [ 0.9774046  -0.9745886  -0.99975403]
 [-0.98518379  0.97198006 -0.98090191]
 [-0.99973935 -0.9949831   0.98975169]
 [-0.98859148  0.98949001 -0.98592242]
 [-0.99981112 -0.9882818   0.98786858]
 [ 0.99518881 -0.99646095 -0.99983611]
 [-0.9998269  -0.97879207  0.98433833]]
============W modificat==========
[[ -4.7256

 [ 11.12441494  -4.11879339   5.54855161]]
0.0013036706617015911
============O==========
[[ 0.99226091 -0.995158   -0.9997864 ]
 [-0.97922328  0.97539879 -0.98807372]
 [ 0.97830995 -0.97558462 -0.99976616]
 [-0.9858177   0.97307574 -0.98162908]
 [-0.99975266 -0.99523969  0.99019369]
 [-0.98912293  0.98999581 -0.98651194]
 [-0.9998215  -0.98879173  0.98835969]
 [ 0.99545323 -0.99666339 -0.99984401]
 [-0.99983671 -0.9795999   0.98492932]]
============W modificat==========
[[ -4.7373567   11.14627876   4.97252891]
 [-11.12012994 -12.03603439  -5.84951584]
 [ 11.12557982  -4.11883657   5.54915398]]
0.001302264967618188
============O==========
[[ 0.99226597 -0.99516138 -0.99978653]
 [-0.97923402  0.97541143 -0.98808003]
 [ 0.97832113 -0.97559695 -0.99976631]
 [-0.98582551  0.97308931 -0.98163809]
 [-0.99975282 -0.99524285  0.99019915]
 [-0.98912947  0.99000203 -0.98651923]
 [-0.99982163 -0.98879803  0.98836577]
 [ 0.99545647 -0.99666587 -0.9998441 ]
 [-0.99983683 -0.97960991  0.98493664]]
=

============O==========
[[ 0.99261764 -0.99539655 -0.99979557]
 [-0.97998416  0.97629566 -0.98852139]
 [ 0.97910233 -0.9764597  -0.99977672]
 [-0.9863706   0.9740386  -0.98226914]
 [-0.99976417 -0.99546261  0.9905808 ]
 [-0.98958469  0.99043619 -0.98702884]
 [-0.99983044 -0.98923825  0.98879097]
 [ 0.99568114 -0.99683799 -0.99985088]
 [-0.99984515 -0.9803113   0.98544976]]
============W modificat==========
[[ -4.74799591  11.2409984    5.01556402]
 [-11.21141321 -12.1378649   -5.89927462]
 [ 11.20971347  -4.12196296   5.5926585 ]]
0.001204846057757162
============O==========
[[ 0.99262211 -0.99539953 -0.99979569]
 [-0.97999373  0.97630696 -0.98852703]
 [ 0.9791123  -0.97647074 -0.99977685]
 [-0.98637754  0.97405074 -0.98227722]
 [-0.99976432 -0.9954654   0.99058567]
 [-0.98959048  0.99044172 -0.98703535]
 [-0.99983055 -0.98924387  0.9887964 ]
 [ 0.99568398 -0.99684017 -0.99985097]
 [-0.99984526 -0.98032028  0.98545633]]
============W modificat==========
[[ -4.7481324   11.24221283   5.

 [-0.99985278 -0.98096794  0.98593017]]
============W modificat==========
[[ -4.75813182  11.33113527   5.05650606]
 [-11.29857365 -12.23505493  -5.94676727]
 [ 11.29007009  -4.12496267   5.63420686]]
0.0011189369569830014
============O==========
[[ 0.99294591 -0.99561592 -0.99980407]
 [-0.98069092  0.97713158 -0.98893836]
 [ 0.97983885 -0.97727581 -0.99978648]
 [-0.98688289  0.97493666 -0.98286701]
 [-0.99977476 -0.99566827  0.99094067]
 [-0.99001102  0.9908434  -0.98750992]
 [-0.99983863 -0.98965328  0.98919293]
 [ 0.99588997 -0.99699804 -0.99985725]
 [-0.99985287 -0.98097604  0.98593609]]
============W modificat==========
[[ -4.75825871  11.33226307   5.05701826]
 [-11.29966592 -12.23627267  -5.94736233]
 [ 11.29107725  -4.12500035   5.63472759]]
0.001117901930727688
============O==========
[[ 0.99294987 -0.99561856 -0.99980418]
 [-0.98069948  0.97714173 -0.98894342]
 [ 0.97984778 -0.97728572 -0.9997866 ]
 [-0.98688909  0.97494757 -0.98287428]
 [-0.99977489 -0.99567075  0.99094504]


 [-0.99986085 -0.98167813  0.98644984]]
============W modificat==========
[[ -4.76946354  11.43179105   5.10221372]
 [-11.39621648 -12.34389495  -5.99995252]
 [ 11.3801175   -4.12834      5.68076231]]
0.0010302434387018426
============O==========
[[ 0.99329087 -0.99584621 -0.99981306]
 [-0.98144085  0.97802135 -0.98938187]
 [ 0.98062089 -0.97814511 -0.99979678]
 [-0.98742509  0.97589328 -0.98350479]
 [-0.99978587 -0.99588487  0.9913227 ]
 [-0.99046056  0.9912733  -0.9880212 ]
 [-0.99984719 -0.99009372  0.98962074]
 [ 0.99610846 -0.99716551 -0.99986397]
 [-0.99986093 -0.98168533  0.98645511]]
============W modificat==========
[[ -4.76958051  11.4328294    5.10268516]
 [-11.39722535 -12.34501933  -6.00050195]
 [ 11.38104804  -4.12837498   5.68124339]]
0.0010293662468917337
============O==========
[[ 0.99329434 -0.99584852 -0.99981316]
 [-0.98144843  0.97803036 -0.98938636]
 [ 0.9806288  -0.97815391 -0.99979688]
 [-0.98743057  0.97590297 -0.98351125]
 [-0.99978599 -0.99588705  0.99132656]