In [117]:
import numpy as np

x = np.array([[45,85],
            [50,43],
            [40,80],
            [55,42],
            [200,43],
            [48,40],
            [195,41],
            [43,87],
            [190,40]])

w1 = np.array([[45.0,85.0]])
w2 = np.array([[200.0,43.0]])
w3 = np.array([[43.0,87.0]])
print("=====Centrul 1=====")
print(w1)
print("===================")
print("=====Centrul 2=====")
print(w2)
print("===================")
print("=====Centrul 3=====")
print(w3)
print("===================")


def f(y,w):
    c = int(abs(w[0]-y[0])+abs(w[1]-y[1]))
    return c


def centru(w,q):
    p = int(len(q))
    a = 0.0
    b = 0.0
    for i in range(0, p):
        a = float(a+q[i][0])
        b = float(b + q[i][1])
    a = round(float(a/p),2)
    b = round(float(b/p),2)
    w[0][0] = float(a)
    w[0][1] = float(b)
    return w

ep = int(input("Nr. epoci = "))

while ep > 0:
    dist1 = []
    dist2 = []
    dist3 = []
    cluster1 = []
    cluster2 = []
    cluster3 = []
    for i in range(0,9):
        a = f(x[i],w1[0])
        b = f(x[i],w2[0])
        c = f(x[i],w3[0])
        dist1.append(a)
        dist2.append(b)
        dist3.append(c)

        if(dist1[i]<dist2[i] and dist1[i]<dist3[i]):
            print("Distanta de la ",x[i],"la ",w1," este :",dist1[i])
            print("Puctul ",x[i],"-> Cluster 1!")
            n = x[i][0]
            m = x[i][1]
            cluster1.append(n)
            cluster1.append(m)

        elif (dist2[i]<dist1[i] and dist2[i]<dist3[i]): 
            print("Distanta de la ",x[i],"la ",w2," este :",dist2[i])
            print("Puctul ",x[i],"-> Cluster 2!") 
            n = x[i][0]
            m = x[i][1]
            cluster2.append(n)
            cluster2.append(m)
        else:
            print("Distanta de la ",x[i],"la ",w3," este :",dist3[i])
            print("Puctul ",x[i],"-> Cluster 3!")
            n = x[i][0]
            m = x[i][1]
            cluster3.append(n)
            cluster3.append(m)


    print("========Cluster 1==========")        
    cluster1 = np.array(cluster1)
    n = int(len(cluster1)/2)
    cluster1 = np.reshape(cluster1, (n, 2))
    print(cluster1)
    print("===========================")
    print("========Cluster 2==========") 
    cluster2 = np.array(cluster2)
    n = int(len(cluster2)/2)
    cluster2 = np.reshape(cluster2, (n, 2))
    print(cluster2)
    print("===========================")
    print("========Cluster 3==========") 
    cluster3 = np.array(cluster3)
    n = int(len(cluster3)/2)
    cluster3 = np.reshape(cluster3, (n, 2))
    print(cluster3)
    print("===========================")

    print("======Noul centru pentru cluster1======")
    w1 = centru(w1,cluster1)
    print(w1)
    print("========================================")

    print("======Noul centru pentru cluster2======")
    w2 = centru(w2,cluster2)
    print(w2)
    print("========================================")
    print("======Noul centru pentru cluster3======")
    w3 = centru(w3,cluster3)
    print(w3)
    print("========================================")
    ep = ep - 1

=====Centrul 1=====
[[45. 85.]]
=====Centrul 2=====
[[200.  43.]]
=====Centrul 3=====
[[43. 87.]]
Nr. epoci = 2
Distanta de la  [45 85] la  [[45. 85.]]  este : 0
Puctul  [45 85] -> Cluster 1!
Distanta de la  [50 43] la  [[45. 85.]]  este : 47
Puctul  [50 43] -> Cluster 1!
Distanta de la  [40 80] la  [[43. 87.]]  este : 10
Puctul  [40 80] -> Cluster 3!
Distanta de la  [55 42] la  [[45. 85.]]  este : 53
Puctul  [55 42] -> Cluster 1!
Distanta de la  [200  43] la  [[200.  43.]]  este : 0
Puctul  [200  43] -> Cluster 2!
Distanta de la  [48 40] la  [[45. 85.]]  este : 48
Puctul  [48 40] -> Cluster 1!
Distanta de la  [195  41] la  [[200.  43.]]  este : 7
Puctul  [195  41] -> Cluster 2!
Distanta de la  [43 87] la  [[43. 87.]]  este : 0
Puctul  [43 87] -> Cluster 3!
Distanta de la  [190  40] la  [[200.  43.]]  este : 13
Puctul  [190  40] -> Cluster 2!
========Cluster 1==========
[[45 85]
 [50 43]
 [55 42]
 [48 40]]
========Cluster 2==========
[[200  43]
 [195  41]
 [190  40]]
========Cluster 3=